# Tensor vs List and Tensor Operations Lab

This notebook explains why tensors are used instead of Python lists and demonstrates tensor operations using **NumPy** and **PyTorch**.

## Why Tensor and Not Python List?

- Tensors store data in contiguous memory blocks for faster computation.
- Support vectorized mathematical operations directly.
- Efficient memory usage compared to Python lists.
- Supports broadcasting and GPU acceleration.
- Widely used in Machine Learning, Deep Learning and Scientific Computing.

## Performance Comparison: List vs NumPy Tensor

In [1]:

import time
import numpy as np

n = 200000

list1 = list(range(n))
list2 = list(range(n))

start = time.time()
res_list = [list1[i] + list2[i] for i in range(n)]
print("List Time:", time.time() - start)

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
res_arr = arr1 + arr2
print("NumPy Tensor Time:", time.time() - start)


List Time: 0.05580711364746094
NumPy Tensor Time: 0.002015352249145508


## Import Libraries

In [2]:

import numpy as np
import torch


## Creating 1D, 2D and 3D Tensors

In [3]:

# NumPy
np_1d = np.array([1, 2, 3])
np_2d = np.array([[1, 2], [3, 4]])
np_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

print("NumPy 1D:", np_1d)
print("NumPy 2D:\n", np_2d)
print("NumPy 3D:\n", np_3d)

# PyTorch
torch_1d = torch.tensor([1, 2, 3])
torch_2d = torch.tensor([[1, 2], [3, 4]])
torch_3d = torch.tensor([[[1,2],[3,4]], [[5,6],[7,8]]])

print("\nTorch 1D:", torch_1d)
print("Torch 2D:\n", torch_2d)
print("Torch 3D:\n", torch_3d)


NumPy 1D: [1 2 3]
NumPy 2D:
 [[1 2]
 [3 4]]
NumPy 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Torch 1D: tensor([1, 2, 3])
Torch 2D:
 tensor([[1, 2],
        [3, 4]])
Torch 3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## Element-wise Operations

In [4]:

a = np.array([1,2,3])
b = np.array([4,5,6])

print("NumPy Add:", a + b)
print("NumPy Multiply:", a * b)

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

print("Torch Add:", x + y)
print("Torch Multiply:", x * y)


NumPy Add: [5 7 9]
NumPy Multiply: [ 4 10 18]
Torch Add: tensor([5, 7, 9])
Torch Multiply: tensor([ 4, 10, 18])


## Indexing, Slicing & Boolean Masking

In [5]:

arr = np.array([[10,20,30],[40,50,60]])
print("Element [0,1]:", arr[0,1])
print("First Row:", arr[0])
print("Submatrix:", arr[:, 1:3])
print("Boolean Masking:", arr[arr > 30])

t = torch.tensor([[10,20,30],[40,50,60]])
print("Torch Element [1,2]:", t[1,2])
print("Torch Masking:", t[t > 30])


Element [0,1]: 20
First Row: [10 20 30]
Submatrix: [[20 30]
 [50 60]]
Boolean Masking: [40 50 60]
Torch Element [1,2]: tensor(60)
Torch Masking: tensor([40, 50, 60])


## PyTorch view, reshape, unsqueeze and squeeze

In [6]:

t = torch.arange(1, 7)
print("Original:", t)

print("View(2,3):\n", t.view(2,3))
print("Reshape(3,2):\n", t.reshape(3,2))
print("Unsqueeze dim=1:\n", t.unsqueeze(1))
print("Squeeze:\n", t.unsqueeze(1).squeeze())


Original: tensor([1, 2, 3, 4, 5, 6])
View(2,3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshape(3,2):
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Unsqueeze dim=1:
 tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Squeeze:
 tensor([1, 2, 3, 4, 5, 6])


## NumPy reshape Comparison

In [7]:

np_arr = np.arange(1,7)
print("NumPy reshape:\n", np_arr.reshape(2,3))


NumPy reshape:
 [[1 2 3]
 [4 5 6]]


## Broadcasting

In [8]:

np_a = np.array([[1,2,3],[4,5,6]])
np_b = np.array([10,20,30])
print("NumPy Broadcasting:\n", np_a + np_b)

torch_a = torch.tensor([[1,2,3],[4,5,6]])
torch_b = torch.tensor([10,20,30])
print("Torch Broadcasting:\n", torch_a + torch_b)


NumPy Broadcasting:
 [[11 22 33]
 [14 25 36]]
Torch Broadcasting:
 tensor([[11, 22, 33],
        [14, 25, 36]])


## In-place vs Out-of-place Operations

In [9]:

# NumPy
a = np.array([1,2,3])
b = a + 5
print("Out-of-place:", b, "Original:", a)

a += 5
print("In-place:", a)

# PyTorch
x = torch.tensor([1,2,3])
y = x + 5
print("Torch Out-of-place:", y, "Original:", x)

x.add_(5)
print("Torch In-place:", x)


Out-of-place: [6 7 8] Original: [1 2 3]
In-place: [6 7 8]
Torch Out-of-place: tensor([6, 7, 8]) Original: tensor([1, 2, 3])
Torch In-place: tensor([6, 7, 8])
